honojs/create-hono

.prettierrc
src/index.ts

This change allows the user to pass their desired template from the command line like so: `npm create hono ./my-hono-app cloudflare-pages`. This is useful for automation where you'd like to skip any interactive prompts.

Accept template name as positional argument from command line

---

src/index.ts

This fixes a regression I introduced last week while working on adding a `--template` argument.
With `0.2.0` running with no args like `npm create hono@latest` will create an `undefined` directory instead of prompting `Directory not empty. Continue?`. The root cause is that it was casting to a String before defaulting to the current directory `.`
This patch fixes that bug.

Fix bug where 'undefined' directory created when no arguments provided

---

src/hook.ts
src/hooks/after-create.ts

* Support RegExp for project names
* Support an array template name for `addHook`
* Some refactoring

feat: regexp for project name & array template name for `addHook`

---

.gitignore
package.json
src/github.ts
src/hook.ts
src/hooks/after-create.ts
src/hooks/dependencies.test.ts
src/hooks/dependencies.ts
src/index.ts
yarn.lock

feat: automate installing dependencies

---

.github/workflows/ci.yml

Node.js 19 is a "Current" release, and the support expired. We can remove this from CI.

ci: remove Node.js 19 CI

---

src/hooks/dependencies.ts

This allows to run this command and skip all prompts. Useful when called from a script.
```bash
pnpm create hono my-app --template x-basic --no-install --pm pnpm
```

fix(dependencies): handle --no-install flag properly

---

src/hooks/dependencies.test.ts
src/hooks/dependencies.ts

Check if the package manager is installed by running its command with `--version`, and only show installed package managers in choices.

feat(dependencies): show only installed package managers in choices

---

src/index.ts

Hi
I have removed the loop that retrieves template names from templateDirs and directly assigned the template names to the templates variable, which now contains the template names.
This change makes the code more readable by reducing the number of lines

refactor(main): remove unnecessary forEach

---

src/hooks/dependencies.ts

Hide the install dependencies option if no package manager is installed.
I have tested it manually and it works fine.
Thanks to @ryuapp for pointing out this issue!
Closes #45

feat(dependencies): hide install option if no package manager is installed.

---

build.ts

This PR will reduce the build size and the time it takes to run `create-hono`.
- https://github.com/goisaki/create-hono/pull/49/commits/78d5a5a22e0f5c0e52f3650abd61ac771ad1fa9b - Enable the `minify` option in esbuild
- 742 KB -> 350 KB

perf: Reduce build size

---

build.ts

In #49, it changed to building with minifier, but as a result debugging became difficult.
It is better not to minify due to reports from users.

fix: don't minify binary file

---

src/index.ts

Closes #56 
Now the `projectName` is getting assigned after `target`, so `.` value can be assigned basename.

fix: assign projectName after target is defined

---

src/hooks/after-create.test.ts
src/hooks/after-create.ts

Closes #58 
Updates the `compatibility_date` in the Workers `wrangler.toml` file to the current date.

feat(workers): set compatibility date to current date

---

package.json
src/hooks/dependencies.ts
src/index.ts
yarn.lock

feat: switched from yargs-parser to commander

---

README.md

Hey, forgot to update the readme in #64 PR
Should I also add the `-V` and `-h`, for version and help in the readme?

chore: updated the readme

---

src/hooks/dependencies.ts
src/index.ts

Closes #36 
There are 2 events that matter - 
1. Template download complete
2. Dependencies installed
Whenever an event is completed `.emit()` function is called and the `.on()` event handler takes it from there.

feat: confirm all questions before init repo

---

src/index.ts

This small PR fixes minor issue for creating project where as Target directory "./" is provided.
project name in package.json is set to "." after providing "./" as Target directory:
after my fix project name in package.json is properly set to current directory name:

fix: projectName for "./" target

---

README.md
src/hooks/dependencies.ts

Related: #73 
As shown in the issue below, Deno has npm compatibility but it does not work locally, so no tests are currently being added.
https://github.com/denoland/deno/issues/15624

feat: support for `deno install`

---

src/hooks/dependencies.ts

Fix https://github.com/honojs/hono/issues/3503
I’m sorry. Old Deno cannot check the version with -`v`, causing errors for some users.
This PR fixes to ~~check the version with `-V` and`~~ not terminate the command if an error occurs.
Ref: https://github.com/denoland/deno/issues/5289#issuecomment-2150513464

fix: old deno gives an error when using `deno -v`

---

src/index.ts

- :bug: Added `process.exit(0)` to cleanly terminate the Node.js process once project files are copied.
- :white_check_mark: Prevents hanging processes after file operations are complete.

fix: :bug: ensure process exits after copying project files

---

src/hook.ts
src/hooks/after-create.test.ts
src/hooks/after-create.ts
src/hooks/dependencies.ts
src/index.ts

Closes #52 
If the users haven't said _yes_ to installation, we may not be able to get the package manager. For that, I have made `npm` the default value.

fix: resolved npm_execpath issue

---

src/hooks/after-create.test.ts
src/hooks/after-create.ts

- `.json`
- `.jsonc`
- `.toml`

feat: updated hooks to handle new wrangler file formats

---

src/hooks/after-create.test.ts
src/hooks/after-create.ts

`compatibility_date` is not replaced with the correct date for `wrangler.json`. This PR will fix it and update the test to check `wrangler.json` and not only `wrangler.toml`.

fix: replace `compatibility_date` for `wrangler.json`

---

.github/workflows/check-template-branch.yml
src/index.ts

This PR updates the `ref` in the template configuration. The `ref` now dynamically points to the versioned branch (e.g., `v0.15`) in the `honojs/starter` repository based on the `create-hono` package version. If the corresponding branch does not exist in the `honojs/starter` repository, it will throw an error in the GitHub Actions workflow.

chore: check the latest branch of `honojs/starter`

---

.eslintrc.cjs
.github/workflows/ci.yml
bun.lock
eslint.config.mjs
package.json
src/hooks/after-create.test.ts
src/hooks/dependencies.test.ts
src/hooks/dependencies.ts
src/index.ts

Update to use latest packages except for execa and giget. Source codes is refactored with some package updates.
These are some of the steps we are taking to update to giget v2.
Regarding #85, I still couldn't solve the problem, so I've update this development environment.

chore: bump up dependencies to latest

---

src/hooks/dependencies.test.ts

Hi @yusukebe !
This pull request includes a change to the `dependencies.test.ts` file to update the package manager used for running the build command.
* [`src/hooks/dependencies.test.ts`](diffhunk://#diff-da313a0aeea2d94d2265b6c2e28b244a106540aee8f8f97b880927937ee5d7b0L34-R34): Changed the package manager from `yarn` to `bun` for running the build command.

chore: use `bun` for building instead of `yarn`

---

bun.lock
package.json

Remove tsx dependency and update build script to use bun directly for executing build.ts. This simplifies dependencies while leveraging the bun runtime that's already a project requirement.

build: replace tsx with bun for build script

---

.github/workflows/ci.yml

This pr deprecates node 18 and add a support for node 24

ci: deprecate node 18 and add node 24

---

src/index.ts

I stumbled across this when choosing the target directory as `.` (current dir) when creating a new project
This PR does not show this console log when the target directory is current

fix: Do not show the info log of `cd .`

---

bun.lock
package.json
src/hooks/dependencies.ts
tsconfig.json

Hi @yusukebe !
This pr replaces `execa` to [`nano-spawn`](https://www.npmjs.com/package/nano-spawn). As a result, the `bin` size is 0.5MB smaller.
I don't modify the test code because it is just works fine.
Also `nano-spawn` is esm only library and the previous tsconfig doesn't work for getting type info of `nano-spawn`, so I modified the `moduleResolution` to `bundler`

perf: replace execa to nano-spawn
